import XIcon from './x-icon.svg';
import LineIcon from './line-icon.svg';
import TranslateIcon from './translate-icon.svg';
import TranslateSmallIcon from './translate-small-icon.svg';
import SearchIcon from './search-icon.svg';
import MenuIcon from './menu-icon.svg';
import LogoIcon from './logo-icon.svg';
import LogoCircleIcon from './logo-circle-icon.svg';
import CircleXIcon from './circle-x-icon.svg';
import ResetIcon from './reset-icon.svg';
import ResetIconSmall from './reset-icon-small.svg';
import ArrowIcon from './arrow-icon.svg';
import PlusIcon from './plus-icon.svg';
import CheckIcon from './check-icon.svg';
import GithubIcon from './github-icon.svg';
import TistoryIcon from './tistory-icon.svg';
import MailIcon from './mail-icon.svg';
import FileIcon from './file-icon.svg';
import FavoriteFillIcon from './favorite-fill.svg';
import FavoriteEmptyIcon from './favorite-empty.svg';
import Logo from './logo.png';

export { XIcon, TranslateIcon, TranslateSmallIcon, SearchIcon, MenuIcon, LogoIcon, LogoCircleIcon, CircleXIcon, ResetIcon, ResetIconSmall, ArrowIcon, PlusIcon, CheckIcon, Logo, GithubIcon, TistoryIcon, MailIcon, FileIcon, LineIcon, FavoriteFillIcon, FavoriteEmptyIcon };